plugins {
    id 'com.android.application'
}

android {
    namespace 'com.stagetostardom.game'
    compileSdk 34

    defaultConfig {
        applicationId 'com.stagetostardom.game'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '7.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
